In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame([
    {"iphone": 1, "Galaxy": 5},
    {"iphone": 2, "Galaxy": 10},
    {"iphone": 3, "Galaxy": 50},
], index=["doc1", "doc2", "doc3"])

In [3]:
df

      iphone  Galaxy
doc1       1       5
doc2       2      10
doc3       3      50

In [7]:
df.loc["doc2":"doc2"]

      iphone  Galaxy
doc2       2      10

In [8]:
from sklearn.metrics.pairwise import cosine_similarity ,cosine_distances

In [12]:
cosine_similarity(df.loc["doc1":"doc1"], df.loc["doc2":"doc2"])

array([[1.]])