In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
v=CountVectorizer(ngram_range=(1,3))

In [12]:
arr =['Great things comes with a great scarifies' , 'That\'s is okay' ,'Be brave and go on an adventure', 'what you do today can improve all your tomorows']

In [13]:
v.fit(arr)

CountVectorizer(ngram_range=(1, 3))

In [14]:
v.vocabulary_

{'great': 27,
 'things': 44,
 'comes': 18,
 'with': 54,
 'scarifies': 40,
 'great things': 29,
 'things comes': 45,
 'comes with': 19,
 'with great': 55,
 'great scarifies': 28,
 'great things comes': 30,
 'things comes with': 46,
 'comes with great': 20,
 'with great scarifies': 56,
 'that': 41,
 'is': 34,
 'okay': 36,
 'that is': 42,
 'is okay': 35,
 'that is okay': 43,
 'be': 9,
 'brave': 12,
 'and': 6,
 'go': 24,
 'on': 37,
 'an': 4,
 'adventure': 0,
 'be brave': 10,
 'brave and': 13,
 'and go': 7,
 'go on': 25,
 'on an': 38,
 'an adventure': 5,
 'be brave and': 11,
 'brave and go': 14,
 'and go on': 8,
 'go on an': 26,
 'on an adventure': 39,
 'what': 51,
 'you': 57,
 'do': 21,
 'today': 47,
 'can': 15,
 'improve': 31,
 'all': 1,
 'your': 60,
 'tomorows': 50,
 'what you': 52,
 'you do': 58,
 'do today': 22,
 'today can': 48,
 'can improve': 16,
 'improve all': 32,
 'all your': 2,
 'your tomorows': 61,
 'what you do': 53,
 'you do today': 59,
 'do today can': 23,
 'today can improve': 49,
 'can improve all': 17,
 'improve all your': 33,
 'all your tomorows': 3}

In [15]:
import spacy

In [17]:
nlp =spacy.load('en_core_web_sm')

In [37]:
def preprocessing(arr) :
    text=""
    text=" ".join(arr)
    doc =nlp(text)
    filtered_token=[]
    for token in doc :
        
        if token.is_stop and token.is_punct :
            continue
        else : 
            filtered_token.append(token.lemma_)
    final =" ".join(filtered_token)     
    return final

In [38]:
text =preprocessing(arr)

In [39]:
print(text)

great thing come with a great scarifie that be be okay be brave and go on an adventure what you do today can improve all your tomorow

In [40]:
v.fit([text])

CountVectorizer(ngram_range=(1, 3))

In [41]:
v.vocabulary_

{'great': 34,
 'thing': 54,
 'come': 25,
 'with': 64,
 'scarifie': 48,
 'that': 51,
 'be': 12,
 'okay': 42,
 'brave': 19,
 'and': 9,
 'go': 31,
 'on': 45,
 'an': 6,
 'adventure': 0,
 'what': 61,
 'you': 67,
 'do': 28,
 'today': 57,
 'can': 22,
 'improve': 39,
 'all': 3,
 'your': 70,
 'tomorow': 60,
 'great thing': 37,
 'thing come': 55,
 'come with': 26,
 'with great': 65,
 'great scarifie': 35,
 'scarifie that': 49,
 'that be': 52,
 'be be': 13,
 'be okay': 17,
 'okay be': 43,
 'be brave': 15,
 'brave and': 20,
 'and go': 10,
 'go on': 32,
 'on an': 46,
 'an adventure': 7,
 'adventure what': 1,
 'what you': 62,
 'you do': 68,
 'do today': 29,
 'today can': 58,
 'can improve': 23,
 'improve all': 40,
 'all your': 4,
 'your tomorow': 71,
 'great thing come': 38,
 'thing come with': 56,
 'come with great': 27,
 'with great scarifie': 66,
 'great scarifie that': 36,
 'scarifie that be': 50,
 'that be be': 53,
 'be be okay': 14,
 'be okay be': 18,
 'okay be brave': 44,
 'be brave and': 16,
 'brave and go': 21,
 'and go on': 11,
 'go on an': 33,
 'on an adventure': 47,
 'an adventure what': 8,
 'adventure what you': 2,
 'what you do': 63,
 'you do today': 69,
 'do today can': 30,
 'today can improve': 59,
 'can improve all': 24,
 'improve all your': 41,
 'all your tomorow': 5}

In [45]:
v.transform(["Great things comes with a great scarifies"]).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 0]])

In [47]:
import pandas as pd

In [48]:
df= pd.read_json("news_dataset.json")

In [49]:
df.shape

(12695, 2)

In [50]:
df.head(10)

                                                text  category
0  Watching Schrödinger's Cat Die University of C...   SCIENCE
1     WATCH: Freaky Vortex Opens Up In Flooded Lake    SCIENCE
2  Entrepreneurs Today Don't Need a Big Budget to...  BUSINESS
3  These Roads Could Recharge Your Electric Car A...  BUSINESS
4  Civilian 'Guard' Fires Gun While 'Protecting' ...     CRIME
5  Trump Pays Penalty For Ethically Questionable ...  BUSINESS
6                          LIVE: Argentina vs. Iran     SPORTS
7  9 Tips for Making Your Blog Better in 2015 New...  BUSINESS
8  Man Arrested Over Threats To CNN:  'Fake News....     CRIME
9  Here's Why Coffee Makes You Have To Poop It hi...   SCIENCE

In [ ]:
#balancing the data
df.category.value_counts()

category
BUSINESS    4254
SPORTS      4167
CRIME       2893
SCIENCE     1381
Name: count, dtype: int64

In [53]:
min= 1381

In [55]:
df_BUSINESS=df[df.category=="BUSINESS"].sample(min,random_state=1234)
df_SPORTS =df[df.category=="SPORTS"].sample(min,random_state=1234)
df_CRIME =df[df.category=="CRIME"].sample(min,random_state=1234)
df_SCIENCE =df[df.category=="SCIENCE"].sample(min,random_state=1234)

In [56]:
Balance_df=pd.concat([df_BUSINESS,df_CRIME,df_SCIENCE,df_SPORTS])

In [57]:
Balance_df.shape

(5524, 2)

In [58]:
Balance_df.category.value_counts()

category
BUSINESS    1381
CRIME       1381
SCIENCE     1381
SPORTS      1381
Name: count, dtype: int64

In [60]:
Balance_df.head()

                                                    text  category
9196                 Krugman: We Should 'Soak The Rich'   BUSINESS
3111                Krugman: Why America Is Still Stuck   BUSINESS
10567  Bay Area School Gets Rich Quick On Snapchat In...  BUSINESS
5575   Is It Safe To Eat At Chipotle After The E. Col...  BUSINESS
1332   Leaked Document Shows Strong Business Support ...  BUSINESS